stages:
  - test

tests:
  stage: test
  image: mcr.microsoft.com/playwright/python:v1.39.0-jammy
  script:
    - "pip install -r requirements.txt"
    - "pip install playwright"
    - "playwright install"
    - "python main.py"

