stages:
  - test

tests:
  stage: test
  image: mcr.microsoft.com/playwright/python:v1.39.0-jammy
  script:
      - python -m pip install --upgrade pip
      - pip install -r local-requirements.txt
      - python main.py
  
  